name: pdf_flutter
description: Displaying PDF from Network, File and assets easily like we display Image in Flutter Widget.
version: 1.1.0
author: Laxman Bhattarai (erluxman) <erluxman@gmail.com>
homepage: https://github.com/erluxman/pdf_flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  pedantic: ^1.9.0
  path_provider: ^1.6.11
  flutter_cache_manager: ^1.4.1
  http: ^0.12.1
  uuid: ^2.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.erluxman.pdf_flutter
        pluginClass: PdfFlutterPlugin
      ios:
        pluginClass: PdfFlutterPlugin